/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "dusk.login": [
        {
            "name": "userId",
            "required": true
        },
        {
            "name": "guard",
            "required": false
        }
    ],
    "dusk.logout": [
        {
            "name": "guard",
            "required": false
        }
    ],
    "dusk.user": [
        {
            "name": "guard",
            "required": false
        }
    ],
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "login": [],
    "login.usuario": [],
    "registro": [],
    "store.usuario": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "logout": [],
    "home": [],
    "personas.index": [],
    "personas.create": [],
    "personas.store": [],
    "personas.show": [
        {
            "name": "persona",
            "required": true
        }
    ],
    "personas.edit": [
        {
            "name": "persona",
            "required": true
        }
    ],
    "personas.update": [
        {
            "name": "persona",
            "required": true
        }
    ],
    "personas.destroy": [
        {
            "name": "persona",
            "required": true
        }
    ],
    "empresas.index": [],
    "empresas.create": [],
    "empresas.store": [],
    "empresas.show": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.edit": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.update": [
        {
            "name": "empresa",
            "required": true
        }
    ],
    "empresas.destroy": [
        {
            "name": "empresa",
            "required": true
        }
    ]
}
}
export {};
